name: edudoor_jobseeker
description: "Edudoor Jobseeker App."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.0
  flutter_bloc: ^8.1.5
  logger: ^2.3.0
  get: ^4.6.6
  connectivity_plus: ^6.0.3
  lottie: ^3.1.1
  flutter_svg: ^2.0.10+1
  pinput: ^4.0.0
  flutter_secure_storage: ^9.1.1
  dio: ^5.4.3+1
  phosphor_flutter: ^2.1.0
  firebase_core: ^2.31.0
  firebase_analytics: ^10.10.5
  firebase_crashlytics: ^3.5.5
  firebase_messaging: ^14.9.2
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  socket_io_client: ^2.0.3+1
  device_info_plus: ^10.1.0
  flutter_blurhash: ^0.8.2
  app_links: ^6.1.1
  uuid: ^4.4.0
  easy_stepper: ^0.8.5
  gap: ^3.0.1
  image_picker: ^1.1.1
  google_maps_place_picker_mb: ^3.1.2
  google_maps_flutter: ^2.6.1
  calendar_date_picker2: ^1.0.2
  geolocator: ^10.1.1
  app_settings: ^5.1.1
  mime: ^1.0.5
  flutter_custom_selector: ^0.0.3
  multi_select_flutter: ^4.1.3
  radio_grouped_buttons: ^1.0.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/edudoor-logo.png"
  remove_alpha_ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/
    - assets/svg/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

    - family: Allison
      fonts:
        - asset: assets/fonts/Allison-Regular.ttf

    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript.ttf

    - family: PoetsenOne
      fonts:
        - asset: assets/fonts/PoetsenOne-Regular.ttf
