import 'package:get/get.dart';

class LocalLanguage extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'title': 'Edudoor Jobseeker',
          'internet_connected': "You're back online!",
          'internet_connected_message': "Stay connected and explore",
          'internet_disconnected': "You're currently offline!",
          'internet_disconnected_message': "Please check your internet connection",
          'copy_right': '@@year Edudoor copyright',
          "login_sign_up": "LOGIN/SIGN UP",
          "get_otp": "GET OTP",
          "job_seeker": "Job Seeker",
          "sign_in_with": "or sign in with",
          'enter_phone_number': 'Enter your phone number',
          'enter_otp': "ENTER OTP",
          'verify_otp': "VERIFY OTP",
          'otp_sent': "We have sent you a OTP on",
          'complete_profile': "Complete profile to apply for job",
          'hr_considers': "HRs only consider consider completed profile",
          'complete_your_profile': "Complete your profile",
          'create_profile': "Create Profile",
          'camera': "Camera",
          'gallery': "Gallery",
          'upload_image': "Upload Image",
          'name': 'Name',
          'email': 'Email',
          'location': "Location",
          "birthday": "Birthday",
          'gender': "Gender",
          'skip': "Skip",
          'basics': "Basics",
          'education': "Education",
          'experience': "Experience",
          'preference': "Preference",
          'resume': 'resume',
          'next': "Next",
          'save': "Save",
          'home': "Home",
          'Jobs': "Jobs",
          'profile': "Profile",
          'applied': "Applied",
          'course': "Course",
          'search_location': 'Search Location',
          'permission_required': "Permission Required",
          'location_permission_required': 'Enable Location Service Location Permission Required',
          'show_nearby': 'Show You Nearby Places',
          'find_location':'Enable location to find your location'
          ,'allow_location': "Allow Location",
          'not_now':"Not Now",
          'email_verified':"Congratulations, your email @email is verified and updated on your account",
          'ok': "OK",
          'verify':'Verify',
          'email_send_to':'We have sent you a OTP on @email',
          'verified': "Verified",

        },
      };
}
