// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWAQvF1qiGhXaUkKOdB5raETA9K2IEWTc',
    appId: '1:342002122095:web:6f2133ef2a4414f3cf3c9a',
    messagingSenderId: '342002122095',
    projectId: 'edudoor-d1eb5',
    authDomain: 'edudoor-d1eb5.firebaseapp.com',
    storageBucket: 'edudoor-d1eb5.appspot.com',
    measurementId: 'G-G4T1X2B79W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeyKrOFW-yuL9Qj-f52qkLoXLPDP8MvGI',
    appId: '1:342002122095:android:fd56f3e1f0d98c4fcf3c9a',
    messagingSenderId: '342002122095',
    projectId: 'edudoor-d1eb5',
    storageBucket: 'edudoor-d1eb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYKpYdJSFCN3OoZ1DzZvHYhsMTT-PVUCg',
    appId: '1:342002122095:ios:538b1e330895155ecf3c9a',
    messagingSenderId: '342002122095',
    projectId: 'edudoor-d1eb5',
    storageBucket: 'edudoor-d1eb5.appspot.com',
    iosBundleId: 'com.example.edudoorJobseeker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYKpYdJSFCN3OoZ1DzZvHYhsMTT-PVUCg',
    appId: '1:342002122095:ios:538b1e330895155ecf3c9a',
    messagingSenderId: '342002122095',
    projectId: 'edudoor-d1eb5',
    storageBucket: 'edudoor-d1eb5.appspot.com',
    iosBundleId: 'com.example.edudoorJobseeker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWAQvF1qiGhXaUkKOdB5raETA9K2IEWTc',
    appId: '1:342002122095:web:e1a886267d1b1594cf3c9a',
    messagingSenderId: '342002122095',
    projectId: 'edudoor-d1eb5',
    authDomain: 'edudoor-d1eb5.firebaseapp.com',
    storageBucket: 'edudoor-d1eb5.appspot.com',
    measurementId: 'G-0S7GXFLZRW',
  );
}
